# Generated by Django 4.1.6 on 2023-03-20 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursPilotage',
            fields=[
                ('id_cours', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypePilotage',
            fields=[
                ('id_type', models.IntegerField(primary_key=True, serialize=False)),
                ('libelle_pilotage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_user', models.CharField(max_length=200)),
                ('prenom_user', models.CharField(max_length=300)),
                ('login_user', models.CharField(max_length=400)),
                ('password_user', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VehiculePilotage',
            fields=[
                ('id_vehicule', models.IntegerField(primary_key=True, serialize=False)),
                ('marque_vehicule', models.CharField(max_length=200)),
                ('model_vehicule', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.IntegerField(primary_key=True, serialize=False)),
                ('date_reservation', models.DateField()),
                ('heure_deb_reservation', models.DateTimeField()),
                ('heure_fin_reservation', models.DateTimeField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.courspilotage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.user')),
            ],
        ),
        migrations.AddField(
            model_name='courspilotage',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.typepilotage'),
        ),
        migrations.AddField(
            model_name='courspilotage',
            name='id_vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.vehiculepilotage'),
        ),
    ]
