# Generated by Django 4.1.6 on 2023-03-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courspilotage',
            name='titre_cours',
            field=models.CharField(default='Cours de Pilotage', max_length=400),
        ),
    ]
