# Generated by Django 4.1.6 on 2023-04-03 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_courspilotage_titre_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcolePilotage',
            fields=[
                ('id_ecole', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_ecole', models.CharField(default='Epsi', max_length=300)),
                ('adresse_ecole', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='courspilotage',
            name='id_ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.ecolepilotage'),
        ),
    ]
