# Generated by Django 4.1.6 on 2023-04-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_ecolepilotage_courspilotage_id_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='courspilotage',
            name='descriptif_cours',
            field=models.TextField(default=''),
        ),
    ]
